### ISSUE TITLE
the loss is NAN 

### ISSUE THREAD

**Issue by gittiming** [yuleiniu/rva#13]
Follow the operation process of github， the loss will be nan at 5 epoch. I lower the learning rate, but the same situation will occur.
![image](https://user-images.githubusercontent.com/29085531/79187358-9de80980-7e4e-11ea-8155-460cf47ebb8f.png)

**Comment by weichentangming** [comment]
![image](https://user-images.githubusercontent.com/29085531/79188182-f1f3ed80-7e50-11ea-81fb-1c6a2a8b92a3.png)
